<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#f7f4ef">
    <title>MyRaces — {{ __('landing.app_title') }}</title>
    @php($appUrl = rtrim(config('app.url'), '/'))
    <meta name="description" content="{{ __('landing.meta_description') }}">
    <link rel="canonical" href="{{ $appUrl }}/">
    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=barlow-condensed:500,600,700,800&family=barlow:400,500,600,700&display=swap" rel="stylesheet">
    @vite(['resources/css/app.css', 'resources/js/app.js'])
    <style>
        :root { --red:#d9202c; --red-dark:#b41021; --ink:#171719; --paper:#f7f4ef; --cream:#fffdf9; --line:#ded9d0; --muted:#64635f; --green:#0c7d57; --font-display:'Barlow Condensed', sans-serif; --font-body:'Barlow', sans-serif; }
        html { scroll-behavior:smooth; } body { background:var(--paper); color:var(--ink); font-family:var(--font-body); } a,button { touch-action:manipulation; }
        .site-header { background:rgba(247,244,239,.9); backdrop-filter:blur(16px); } .logo-symbol { display:grid; width:34px; height:34px; place-items:center; border-radius:50%; background:var(--red); color:white; }
        .display { font-family:var(--font-display); font-weight:800; letter-spacing:-.045em; text-transform:uppercase; } .label { font-size:.74rem; font-weight:700; letter-spacing:.12em; text-transform:uppercase; }
        .nav-link { color:#4e4e4a; transition:color .18s ease; } .nav-link:hover { color:var(--red); } .focus-ring:focus-visible { outline:3px solid var(--red); outline-offset:4px; }
        .cta { display:inline-flex; min-height:48px; align-items:center; justify-content:center; gap:.65rem; border:2px solid var(--ink); padding:.72rem 1.1rem; font-size:.93rem; font-weight:700; transition:transform .18s ease,background-color .18s ease,color .18s ease; } .cta:hover { transform:translateY(-2px); } .cta-red { border-color:var(--red); background:var(--red); color:white; } .cta-red:hover { background:var(--red-dark); } .cta-outline:hover { background:var(--ink); color:white; }
        .hero-ruler { background:repeating-linear-gradient(90deg,transparent 0 30px,rgba(23,23,25,.14) 30px 31px); } .track-field { background:var(--red); overflow:hidden; } .track-field::after { position:absolute; right:-15%; top:-35%; width:90%; height:165%; border:2px solid rgba(255,255,255,.42); border-radius:50%; content:''; transform:rotate(-21deg); }
        .track-field::before { position:absolute; right:-8%; top:-24%; width:66%; height:142%; border:2px solid rgba(255,255,255,.42); border-radius:50%; content:''; transform:rotate(-21deg); } .result-card { box-shadow:12px 12px 0 #171719; } .metric { border-left:1px solid var(--line); } .feature { border:1px solid var(--line); background:var(--cream); transition:transform .2s ease,box-shadow .2s ease; } .feature:hover { transform:translateY(-5px); box-shadow:8px 8px 0 var(--red); }
        .timeline::before { position:absolute; top:0; bottom:0; left:11px; width:2px; background:#ded9d0; content:''; } .timeline-dot { box-shadow:0 0 0 5px var(--cream); } .finish-panel { background:var(--ink); color:white; } .number { font-variant-numeric:tabular-nums; }
        @media (prefers-reduced-motion:reduce) { *,::before,::after { scroll-behavior:auto!important; transition-duration:.01ms!important; animation-duration:.01ms!important; } }
    </style>
</head>
<body>
    <a href="#main" class="sr-only focus:not-sr-only focus:absolute focus:left-5 focus:top-5 focus:z-[100] focus:bg-white focus:px-4 focus:py-3 focus:text-black">{{ __('landing.s2_skip') }}</a>
    <header class="site-header fixed inset-x-0 top-0 z-50 border-b border-[#ded9d0]"><div class="mx-auto flex h-[70px] max-w-7xl items-center justify-between px-5 sm:px-8"><a href="{{ route('home') }}" class="focus-ring flex items-center gap-2.5 font-bold tracking-[-.04em]" aria-label="MyRaces"><span class="logo-symbol" aria-hidden="true"><svg class="h-5 w-5" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.4"><path d="M4 17c3-8 6-10 16-10M4 12c3-4 6-5 12-5"/><circle cx="5" cy="18" r="1.4" fill="currentColor" stroke="none"/></svg></span><span>myraces</span></a><nav class="hidden gap-7 text-sm font-semibold md:flex" aria-label="{{ __('landing.s2_nav_aria') }}"><a class="nav-link focus-ring" href="#features">{{ __('landing.s2_nav_features') }}</a><a class="nav-link focus-ring" href="#season">{{ __('landing.s2_nav_season') }}</a></nav><div class="flex items-center gap-3 text-sm font-semibold"><div class="hidden gap-1.5 text-xs sm:flex"><a class="focus-ring {{ app()->getLocale() === 'es' ? 'text-[#171719]' : 'text-[#86837d]' }}" href="{{ route('language.switch', 'es') }}">ES</a><span aria-hidden="true">/</span><a class="focus-ring {{ app()->getLocale() === 'en' ? 'text-[#171719]' : 'text-[#86837d]' }}" href="{{ route('language.switch', 'en') }}">EN</a></div>@auth<a href="{{ route('dashboard') }}" class="cta cta-outline focus-ring !min-h-[40px] !px-4">{{ __('landing.go_to_dashboard') }}</a>@else<a href="{{ route('login') }}" class="nav-link focus-ring hidden sm:block">{{ __('landing.sign_in') }}</a><a href="{{ route('register') }}" class="cta cta-outline focus-ring !min-h-[40px] !px-4">{{ __('landing.web_access') }}</a>@endauth</div></div></header>
    <main id="main">
        <section class="pt-[70px]"><div class="mx-auto grid max-w-7xl lg:grid-cols-[1fr_.92fr]"><div class="px-5 pb-16 pt-16 sm:px-8 sm:pb-20 sm:pt-24 lg:py-28"><p class="label text-[#b41021]">{{ __('landing.s2_kicker') }}</p><h1 class="display mt-4 max-w-2xl text-[clamp(4rem,8.5vw,8.75rem)] leading-[.79]">{{ __('landing.s2_title_first') }} <span class="text-[#d9202c]">{{ __('landing.s2_title_second') }}</span></h1><p class="mt-8 max-w-lg text-lg leading-8 text-[#55534e]">{{ __('landing.s2_intro') }}</p><div class="mt-9 flex flex-wrap gap-3"><span class="cta cta-red cursor-default" aria-label="{{ __('landing.s2_coming_aria') }}"><svg class="h-5 w-5" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M17.05 12.54c-.03-2.62 2.14-3.89 2.24-3.95-1.22-1.78-3.11-2.02-3.78-2.05-1.59-.17-3.14.95-3.95.95-.83 0-2.08-.93-3.42-.9-1.73.03-3.35 1.03-4.24 2.59-1.84 3.18-.47 7.85 1.3 10.44.89 1.27 1.93 2.69 3.3 2.64 1.34-.06 1.84-.85 3.46-.85 1.6 0 2.07.85 3.47.82 1.44-.02 2.35-1.28 3.2-2.57 1.03-1.46 1.44-2.9 1.46-2.98-.03-.01-2.78-1.06-2.84-4.14Z"/></svg>{{ __('landing.s2_coming') }}</span><a class="cta cta-outline focus-ring" href="#features">{{ __('landing.s2_discover') }}</a></div><p class="mt-5 text-sm font-medium text-[#77736c]">{{ __('landing.s2_caption') }}</p></div>
            <div class="track-field relative min-h-[470px] px-5 py-12 sm:px-10 lg:min-h-full"><div class="hero-ruler absolute inset-x-0 bottom-0 h-10 opacity-40"></div><div class="relative z-10 mx-auto max-w-[420px] pt-4"><p class="label text-white/75">{{ __('landing.s2_preview_label') }}</p><div class="result-card mt-4 bg-[#fffdf9] p-5 text-[#171719] sm:p-6"><div class="flex items-start justify-between border-b-2 border-[#171719] pb-5"><div><p class="label text-[#d9202c]">{{ __('landing.s2_result_label') }}</p><h2 class="mt-2 text-xl font-bold tracking-[-.035em]">Media Maratón Bilbao</h2></div><span class="number text-3xl font-bold tracking-[-.07em]">21K</span></div><div class="mt-8 flex items-end justify-between"><div><p class="label text-[#6b6861]">{{ __('landing.s2_official_time') }}</p><p class="number mt-1 font-[var(--font-display)] text-6xl font-bold leading-none tracking-[-.06em]">01:42:18</p></div><span class="mb-1 bg-[#d9202c] px-3 py-2 text-xs font-bold uppercase tracking-[.08em] text-white">{{ __('landing.s2_pb') }}</span></div><div class="mt-7 grid grid-cols-3 border-t border-[#ded9d0] pt-4 text-center"><div><p class="number text-xl font-bold">18</p><p class="label mt-1 text-[.58rem] text-[#77736c]">{{ __('landing.s2_races') }}</p></div><div class="metric"><p class="number text-xl font-bold">1.284</p><p class="label mt-1 text-[.58rem] text-[#77736c]">{{ __('landing.s2_km') }}</p></div><div class="metric"><p class="number text-xl font-bold">03</p><p class="label mt-1 text-[.58rem] text-[#77736c]">{{ __('landing.s2_pbs') }}</p></div></div></div><p class="mt-7 max-w-[320px] text-base font-medium leading-6 text-white">{{ __('landing.s2_preview_text') }}</p></div></div></div></section>
        <section class="border-y border-[#ded9d0] bg-[#fffdf9]"><div class="mx-auto grid max-w-7xl divide-y divide-[#ded9d0] sm:grid-cols-3 sm:divide-x sm:divide-y-0">@foreach ([['01','s2_strip_1'],['02','s2_strip_2'],['03','s2_strip_3']] as [$number,$text])<div class="flex items-center gap-4 px-5 py-6 sm:px-8"><span class="number font-[var(--font-display)] text-3xl font-bold text-[#d9202c]">{{ $number }}</span><p class="font-semibold">{{ __('landing.'.$text) }}</p></div>@endforeach</div></section>
        <section class="px-5 py-24 sm:px-8" id="features"><div class="mx-auto max-w-7xl"><div class="grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><p class="label text-[#b41021]">{{ __('landing.s2_features_kicker') }}</p><h2 class="display mt-4 text-5xl leading-[.84] sm:text-7xl">{{ __('landing.s2_features_title') }}</h2></div><p class="max-w-xl self-end text-lg leading-8 text-[#5a5751]">{{ __('landing.s2_features_intro') }}</p></div><div class="mt-12 grid gap-4 md:grid-cols-3">@foreach ([['calendar','s2_feature_1_title','s2_feature_1_text'],['flag','s2_feature_2_title','s2_feature_2_text'],['chart','s2_feature_3_title','s2_feature_3_text']] as [$icon,$title,$text])<article class="feature p-6 sm:p-7"><span class="label text-[#d9202c]">0{{ $loop->iteration }}</span><div class="mt-14 h-9 text-[#171719]" aria-hidden="true">@if($icon === 'calendar')<svg class="h-9 w-9" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="5" width="18" height="16" rx="1"/><path d="M16 3v4M8 3v4M3 10h18"/></svg>@elseif($icon === 'flag')<svg class="h-9 w-9" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M5 21V4m0 0c5-3 7 3 14 0v10c-7 3-9-3-14 0"/></svg>@else<svg class="h-9 w-9" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M3 20V10m6 10V4m6 16v-7m6 7V7"/></svg>@endif</div><h3 class="mt-7 text-2xl font-bold tracking-[-.04em]">{{ __('landing.'.$title) }}</h3><p class="mt-3 leading-7 text-[#66625b]">{{ __('landing.'.$text) }}</p></article>@endforeach</div></div></section>
        <section class="bg-[#fffdf9] px-5 py-24 sm:px-8" id="season"><div class="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p class="label text-[#b41021]">{{ __('landing.s2_season_kicker') }}</p><h2 class="display mt-4 text-5xl leading-[.84] sm:text-7xl">{{ __('landing.s2_season_title') }}</h2><p class="mt-7 max-w-md text-lg leading-8 text-[#5a5751]">{{ __('landing.s2_season_text') }}</p></div><div class="border-2 border-[#171719] bg-[#fffdf9] p-6 sm:p-8"><div class="flex items-center justify-between border-b-2 border-[#171719] pb-5"><div><p class="label text-[#d9202c]">{{ __('landing.s2_timeline_label') }}</p><h3 class="mt-1 text-xl font-bold">{{ __('landing.s2_timeline_title') }}</h3></div><p class="number text-2xl font-bold">2026</p></div><div class="timeline relative mt-7 space-y-7">@foreach ([['10K Donostia','42:18','s2_done'],['Bilbao Night Marathon','03:24:51','s2_done'],['Zegama–Aizkorri','14 Jun','s2_next']] as [$race,$time,$state])<div class="relative flex items-center justify-between gap-4 pl-8"><span class="timeline-dot absolute left-0 top-1.5 h-6 w-6 rounded-full {{ $loop->last ? 'bg-[#d9202c]' : 'bg-[#0c7d57]' }}"></span><div><p class="font-bold">{{ $race }}</p><p class="mt-1 text-sm text-[#716e68]">{{ __('landing.'.$state) }}</p></div><strong class="number whitespace-nowrap text-lg">{{ $time }}</strong></div>@endforeach</div></div></div></section>
        <section class="px-5 py-16 sm:px-8 sm:py-24"><div class="finish-panel mx-auto grid max-w-7xl overflow-hidden lg:grid-cols-[1fr_.7fr]"><div class="p-8 sm:p-12"><p class="label text-[#ff737a]">{{ __('landing.s2_final_kicker') }}</p><h2 class="display mt-4 max-w-xl text-5xl leading-[.84] sm:text-7xl">{{ __('landing.s2_final_title') }}</h2><p class="mt-7 max-w-lg text-lg leading-8 text-white/70">{{ __('landing.s2_final_text') }}</p><span class="cta cta-red mt-9 cursor-default" aria-label="{{ __('landing.s2_coming_aria') }}">{{ __('landing.s2_final_button') }}</span></div><div class="hidden items-end justify-end bg-[#d9202c] p-10 lg:flex"><p class="font-[var(--font-display)] text-[12rem] font-bold leading-none tracking-[-.1em] text-[#171719]">MR</p></div></div></section>
    </main>
    <footer class="border-t border-[#ded9d0] px-5 py-8 sm:px-8"><div class="mx-auto flex max-w-7xl flex-col justify-between gap-3 text-sm text-[#68655e] sm:flex-row"><p>{{ __('landing.footer_copy', ['year' => now()->year]) }}</p><p>{{ __('landing.footer_tagline') }}</p></div></footer>
</body>
</html>
